// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoData.proto

package com.frizo.lab.netty.pb.app.proto;

public final class ProtoData {
  private ProtoData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.frizo.lab.netty.pb.app.proto.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
     * @return The enum numeric value on the wire for signal.
     */
    int getSignalValue();
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
     * @return The signal.
     */
    com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal getSignal();

    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    int getColumnCount();
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    boolean containsColumn(
        java.lang.String key);
    /**
     * Use {@link #getColumnMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
    getColumn();
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
    getColumnMap();
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */

    com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrDefault(
        java.lang.String key,
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData defaultValue);
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */

    com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.frizo.lab.netty.pb.app.proto.Record}
   */
  public static final class Record extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.frizo.lab.netty.pb.app.proto.Record)
      RecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Record() {
      signal_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Record();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Record(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              signal_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                column_ = com.google.protobuf.MapField.newMapField(
                    ColumnDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
              column__ = input.readMessage(
                  ColumnDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              column_.getMutableMap().put(
                  column__.getKey(), column__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetColumn();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frizo.lab.netty.pb.app.proto.ProtoData.Record.class, com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Builder.class);
    }

    /**
     * Protobuf enum {@code com.frizo.lab.netty.pb.app.proto.Record.Signal}
     */
    public enum Signal
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NODE = 0;</code>
       */
      NODE(0),
      /**
       * <code>STOP = 1;</code>
       */
      STOP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NODE = 0;</code>
       */
      public static final int NODE_VALUE = 0;
      /**
       * <code>STOP = 1;</code>
       */
      public static final int STOP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Signal valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Signal forNumber(int value) {
        switch (value) {
          case 0: return NODE;
          case 1: return STOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Signal>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Signal> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Signal>() {
              public Signal findValueByNumber(int number) {
                return Signal.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.Record.getDescriptor().getEnumTypes().get(0);
      }

      private static final Signal[] VALUES = values();

      public static Signal valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Signal(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.frizo.lab.netty.pb.app.proto.Record.Signal)
    }

    public static final int SIGNAL_FIELD_NUMBER = 1;
    private int signal_;
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
     * @return The enum numeric value on the wire for signal.
     */
    @java.lang.Override public int getSignalValue() {
      return signal_;
    }
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
     * @return The signal.
     */
    @java.lang.Override public com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal getSignal() {
      @SuppressWarnings("deprecation")
      com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal result = com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.valueOf(signal_);
      return result == null ? com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.UNRECOGNIZED : result;
    }

    public static final int COLUMN_FIELD_NUMBER = 2;
    private static final class ColumnDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>newDefaultInstance(
                  com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> column_;
    private com.google.protobuf.MapField<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
    internalGetColumn() {
      if (column_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ColumnDefaultEntryHolder.defaultEntry);
      }
      return column_;
    }

    public int getColumnCount() {
      return internalGetColumn().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */

    @java.lang.Override
    public boolean containsColumn(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetColumn().getMap().containsKey(key);
    }
    /**
     * Use {@link #getColumnMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> getColumn() {
      return getColumnMap();
    }
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> getColumnMap() {
      return internalGetColumn().getMap();
    }
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    @java.lang.Override

    public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrDefault(
        java.lang.String key,
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> map =
          internalGetColumn().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
     */
    @java.lang.Override

    public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> map =
          internalGetColumn().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signal_ != com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.NODE.getNumber()) {
        output.writeEnum(1, signal_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetColumn(),
          ColumnDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signal_ != com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.NODE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, signal_);
      }
      for (java.util.Map.Entry<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> entry
           : internalGetColumn().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
        column__ = ColumnDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, column__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frizo.lab.netty.pb.app.proto.ProtoData.Record)) {
        return super.equals(obj);
      }
      com.frizo.lab.netty.pb.app.proto.ProtoData.Record other = (com.frizo.lab.netty.pb.app.proto.ProtoData.Record) obj;

      if (signal_ != other.signal_) return false;
      if (!internalGetColumn().equals(
          other.internalGetColumn())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
      hash = (53 * hash) + signal_;
      if (!internalGetColumn().getMap().isEmpty()) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + internalGetColumn().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frizo.lab.netty.pb.app.proto.ProtoData.Record prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.frizo.lab.netty.pb.app.proto.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.frizo.lab.netty.pb.app.proto.Record)
        com.frizo.lab.netty.pb.app.proto.ProtoData.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetColumn();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableColumn();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frizo.lab.netty.pb.app.proto.ProtoData.Record.class, com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Builder.class);
      }

      // Construct using com.frizo.lab.netty.pb.app.proto.ProtoData.Record.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signal_ = 0;

        internalGetMutableColumn().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor;
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.Record getDefaultInstanceForType() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.Record.getDefaultInstance();
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.Record build() {
        com.frizo.lab.netty.pb.app.proto.ProtoData.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.Record buildPartial() {
        com.frizo.lab.netty.pb.app.proto.ProtoData.Record result = new com.frizo.lab.netty.pb.app.proto.ProtoData.Record(this);
        int from_bitField0_ = bitField0_;
        result.signal_ = signal_;
        result.column_ = internalGetColumn();
        result.column_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frizo.lab.netty.pb.app.proto.ProtoData.Record) {
          return mergeFrom((com.frizo.lab.netty.pb.app.proto.ProtoData.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frizo.lab.netty.pb.app.proto.ProtoData.Record other) {
        if (other == com.frizo.lab.netty.pb.app.proto.ProtoData.Record.getDefaultInstance()) return this;
        if (other.signal_ != 0) {
          setSignalValue(other.getSignalValue());
        }
        internalGetMutableColumn().mergeFrom(
            other.internalGetColumn());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frizo.lab.netty.pb.app.proto.ProtoData.Record parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frizo.lab.netty.pb.app.proto.ProtoData.Record) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int signal_ = 0;
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
       * @return The enum numeric value on the wire for signal.
       */
      @java.lang.Override public int getSignalValue() {
        return signal_;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
       * @param value The enum numeric value on the wire for signal to set.
       * @return This builder for chaining.
       */
      public Builder setSignalValue(int value) {
        
        signal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
       * @return The signal.
       */
      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal getSignal() {
        @SuppressWarnings("deprecation")
        com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal result = com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.valueOf(signal_);
        return result == null ? com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
       * @param value The signal to set.
       * @return This builder for chaining.
       */
      public Builder setSignal(com.frizo.lab.netty.pb.app.proto.ProtoData.Record.Signal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        signal_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.Record.Signal signal = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignal() {
        
        signal_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> column_;
      private com.google.protobuf.MapField<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
      internalGetColumn() {
        if (column_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ColumnDefaultEntryHolder.defaultEntry);
        }
        return column_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
      internalGetMutableColumn() {
        onChanged();;
        if (column_ == null) {
          column_ = com.google.protobuf.MapField.newMapField(
              ColumnDefaultEntryHolder.defaultEntry);
        }
        if (!column_.isMutable()) {
          column_ = column_.copy();
        }
        return column_;
      }

      public int getColumnCount() {
        return internalGetColumn().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */

      @java.lang.Override
      public boolean containsColumn(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetColumn().getMap().containsKey(key);
      }
      /**
       * Use {@link #getColumnMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> getColumn() {
        return getColumnMap();
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> getColumnMap() {
        return internalGetColumn().getMap();
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */
      @java.lang.Override

      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrDefault(
          java.lang.String key,
          com.frizo.lab.netty.pb.app.proto.ProtoData.PbData defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> map =
            internalGetColumn().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */
      @java.lang.Override

      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getColumnOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> map =
            internalGetColumn().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearColumn() {
        internalGetMutableColumn().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */

      public Builder removeColumn(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableColumn().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData>
      getMutableColumn() {
        return internalGetMutableColumn().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */
      public Builder putColumn(
          java.lang.String key,
          com.frizo.lab.netty.pb.app.proto.ProtoData.PbData value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableColumn().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.frizo.lab.netty.pb.app.proto.PbData&gt; column = 2;</code>
       */

      public Builder putAllColumn(
          java.util.Map<java.lang.String, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData> values) {
        internalGetMutableColumn().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.frizo.lab.netty.pb.app.proto.Record)
    }

    // @@protoc_insertion_point(class_scope:com.frizo.lab.netty.pb.app.proto.Record)
    private static final com.frizo.lab.netty.pb.app.proto.ProtoData.Record DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frizo.lab.netty.pb.app.proto.ProtoData.Record();
    }

    public static com.frizo.lab.netty.pb.app.proto.ProtoData.Record getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Record>
        PARSER = new com.google.protobuf.AbstractParser<Record>() {
      @java.lang.Override
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Record(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Record> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frizo.lab.netty.pb.app.proto.ProtoData.Record getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.frizo.lab.netty.pb.app.proto.PbData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
     * @return The dataType.
     */
    com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType getDataType();

    /**
     * <code>bytes binaryData = 2;</code>
     * @return The binaryData.
     */
    com.google.protobuf.ByteString getBinaryData();
  }
  /**
   * Protobuf type {@code com.frizo.lab.netty.pb.app.proto.PbData}
   */
  public static final class PbData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.frizo.lab.netty.pb.app.proto.PbData)
      PbDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbData.newBuilder() to construct.
    private PbData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbData() {
      dataType_ = 0;
      binaryData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PbData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {

              binaryData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_PbData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.class, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.Builder.class);
    }

    /**
     * Protobuf enum {@code com.frizo.lab.netty.pb.app.proto.PbData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STRING = 0;</code>
       */
      STRING(0),
      /**
       * <code>FLOAT = 1;</code>
       */
      FLOAT(1),
      /**
       * <code>INT = 2;</code>
       */
      INT(2),
      /**
       * <code>FILE = 3;</code>
       */
      FILE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>STRING = 0;</code>
       */
      public static final int STRING_VALUE = 0;
      /**
       * <code>FLOAT = 1;</code>
       */
      public static final int FLOAT_VALUE = 1;
      /**
       * <code>INT = 2;</code>
       */
      public static final int INT_VALUE = 2;
      /**
       * <code>FILE = 3;</code>
       */
      public static final int FILE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return STRING;
          case 1: return FLOAT;
          case 2: return INT;
          case 3: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.frizo.lab.netty.pb.app.proto.PbData.DataType)
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType result = com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.valueOf(dataType_);
      return result == null ? com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.UNRECOGNIZED : result;
    }

    public static final int BINARYDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString binaryData_;
    /**
     * <code>bytes binaryData = 2;</code>
     * @return The binaryData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBinaryData() {
      return binaryData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.STRING.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (!binaryData_.isEmpty()) {
        output.writeBytes(2, binaryData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.STRING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (!binaryData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, binaryData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frizo.lab.netty.pb.app.proto.ProtoData.PbData)) {
        return super.equals(obj);
      }
      com.frizo.lab.netty.pb.app.proto.ProtoData.PbData other = (com.frizo.lab.netty.pb.app.proto.ProtoData.PbData) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getBinaryData()
          .equals(other.getBinaryData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + BINARYDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBinaryData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frizo.lab.netty.pb.app.proto.ProtoData.PbData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.frizo.lab.netty.pb.app.proto.PbData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.frizo.lab.netty.pb.app.proto.PbData)
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_PbData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.class, com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.Builder.class);
      }

      // Construct using com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        binaryData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor;
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getDefaultInstanceForType() {
        return com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.getDefaultInstance();
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData build() {
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData buildPartial() {
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData result = new com.frizo.lab.netty.pb.app.proto.ProtoData.PbData(this);
        result.dataType_ = dataType_;
        result.binaryData_ = binaryData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frizo.lab.netty.pb.app.proto.ProtoData.PbData) {
          return mergeFrom((com.frizo.lab.netty.pb.app.proto.ProtoData.PbData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frizo.lab.netty.pb.app.proto.ProtoData.PbData other) {
        if (other == com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (other.getBinaryData() != com.google.protobuf.ByteString.EMPTY) {
          setBinaryData(other.getBinaryData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frizo.lab.netty.pb.app.proto.ProtoData.PbData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dataType_ = 0;
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType result = com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.valueOf(dataType_);
        return result == null ? com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.frizo.lab.netty.pb.app.proto.ProtoData.PbData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.frizo.lab.netty.pb.app.proto.PbData.DataType dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString binaryData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes binaryData = 2;</code>
       * @return The binaryData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBinaryData() {
        return binaryData_;
      }
      /**
       * <code>bytes binaryData = 2;</code>
       * @param value The binaryData to set.
       * @return This builder for chaining.
       */
      public Builder setBinaryData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        binaryData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes binaryData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinaryData() {
        
        binaryData_ = getDefaultInstance().getBinaryData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.frizo.lab.netty.pb.app.proto.PbData)
    }

    // @@protoc_insertion_point(class_scope:com.frizo.lab.netty.pb.app.proto.PbData)
    private static final com.frizo.lab.netty.pb.app.proto.ProtoData.PbData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frizo.lab.netty.pb.app.proto.ProtoData.PbData();
    }

    public static com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbData>
        PARSER = new com.google.protobuf.AbstractParser<PbData>() {
      @java.lang.Override
      public PbData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frizo.lab.netty.pb.app.proto.ProtoData.PbData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_frizo_lab_netty_pb_app_proto_Record_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_frizo_lab_netty_pb_app_proto_PbData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoData.proto\022 com.frizo.lab.netty.p" +
      "b.app.proto\"\206\002\n\006Record\022?\n\006signal\030\001 \001(\0162/" +
      ".com.frizo.lab.netty.pb.app.proto.Record" +
      ".Signal\022D\n\006column\030\002 \003(\01324.com.frizo.lab." +
      "netty.pb.app.proto.Record.ColumnEntry\032W\n" +
      "\013ColumnEntry\022\013\n\003key\030\001 \001(\t\0227\n\005value\030\002 \001(\013" +
      "2(.com.frizo.lab.netty.pb.app.proto.PbDa" +
      "ta:\0028\001\"\034\n\006Signal\022\010\n\004NODE\020\000\022\010\n\004STOP\020\001\"\227\001\n" +
      "\006PbData\022C\n\010dataType\030\001 \001(\01621.com.frizo.la" +
      "b.netty.pb.app.proto.PbData.DataType\022\022\n\n" +
      "binaryData\030\002 \001(\014\"4\n\010DataType\022\n\n\006STRING\020\000" +
      "\022\t\n\005FLOAT\020\001\022\007\n\003INT\020\002\022\010\n\004FILE\020\003B\rB\tProtoD" +
      "ataH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor,
        new java.lang.String[] { "Signal", "Column", });
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_descriptor =
      internal_static_com_frizo_lab_netty_pb_app_proto_Record_descriptor.getNestedTypes().get(0);
    internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_frizo_lab_netty_pb_app_proto_Record_ColumnEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_frizo_lab_netty_pb_app_proto_PbData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_frizo_lab_netty_pb_app_proto_PbData_descriptor,
        new java.lang.String[] { "DataType", "BinaryData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
